const STORAGE_KEY='mathsversity-encrypted-account-v1';
const $=id=>document.getElementById(id);
let mode='login';
const encoder=new TextEncoder(),decoder=new TextDecoder();
const bytesToBase64=bytes=>btoa(String.fromCharCode(...new Uint8Array(bytes)));
const base64ToBytes=value=>Uint8Array.from(atob(value),char=>char.charCodeAt(0));
const setMessage=(text,type)=>{const box=$('authMessage');box.textContent=text;box.className=`auth-message show ${type}`};
const clearMessage=()=>{$('authMessage').className='auth-message';$('authMessage').textContent=''};
async function deriveKey(password,salt){const material=await crypto.subtle.importKey('raw',encoder.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:210000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function encryptAccount(account,password){const salt=crypto.getRandomValues(new Uint8Array(16));const iv=crypto.getRandomValues(new Uint8Array(12));const key=await deriveKey(password,salt);const encrypted=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,encoder.encode(JSON.stringify(account)));return {version:'1',salt:bytesToBase64(salt),iv:bytesToBase64(iv),data:bytesToBase64(encrypted)}}
async function decryptAccount(record,password){const key=await deriveKey(password,base64ToBytes(record.salt));const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:base64ToBytes(record.iv)},key,base64ToBytes(record.data));return JSON.parse(decoder.decode(plain))}
function saveRecord(record){localStorage.setItem(STORAGE_KEY,JSON.stringify(record));const csv=`version,salt,iv,encrypted_data\n${record.version},${record.salt},${record.iv},${record.data}\n`;localStorage.setItem(`${STORAGE_KEY}-csv`,csv);return csv}
function downloadCsv(csv){const blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='mathsversity-encrypted-user.csv';a.click();URL.revokeObjectURL(url)}
function setMode(next){mode=next;const register=mode==='register';document.querySelectorAll('.register-only').forEach(el=>el.style.display=register?'grid':'none');$('loginTab').classList.toggle('active',!register);$('registerTab').classList.toggle('active',register);$('formEyebrow').textContent=register?'GET STARTED':'WELCOME BACK';$('formTitle').textContent=register?'Create your Mathsversity account':'Sign in to Mathsversity';$('formSubtitle').textContent=register?'Save your learning journey securely on this device.':'Continue where you left off.';$('submitButton').innerHTML=register?'Create account <span>→</span>':'Sign in <span>→</span>';$('footCopy').textContent=register?'Already have an account?':'New to Mathsversity?';$('switchMode').textContent=register?'Sign in instead':'Create an account';$('password').autocomplete=register?'new-password':'current-password';clearMessage()}
$('loginTab').addEventListener('click',()=>setMode('login'));$('registerTab').addEventListener('click',()=>setMode('register'));$('switchMode').addEventListener('click',()=>setMode(mode==='login'?'register':'login'));
$('authForm').addEventListener('submit',async event=>{event.preventDefault();clearMessage();const button=$('submitButton');button.disabled=true;try{const email=$('email').value.trim().toLowerCase(),password=$('password').value;if(mode==='register'){const name=$('name').value.trim();if(!name)throw Error('Please enter your name.');const account={name,email,classLevel:$('classLevel').value,minutes:0,streak:0,hearts:3,createdAt:new Date().toISOString()};const record=await encryptAccount(account,password);const csv=saveRecord(record);sessionStorage.setItem('mathsversity-session-v1',JSON.stringify(account));downloadCsv(csv);setMessage('Account created. Your encrypted CSV backup was downloaded.','success');setTimeout(()=>location.href='index.html',900)}else{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');if(!saved)throw Error('No local account found. Create an account first on this device.');const account=await decryptAccount(saved,password);if(account.email!==email)throw Error('That email does not match this account.');sessionStorage.setItem('mathsversity-session-v1',JSON.stringify({...account,hearts:account.hearts??3}));setMessage('Signed in successfully.','success');setTimeout(()=>location.href='index.html',650)}}catch(error){setMessage(mode==='login'?'Unable to sign in. Check your email and password.':error.message||'Unable to create the account.','error')}finally{button.disabled=false}});
setMode('login');
