(function () {
  const definitions = {
    "3-1": [3, "Array Grid Builder", "Multiplication as arrays", "Build the requested rows and columns to reveal the product.", arrayBuilder],
    "3-2": [3, "Times-Table Race Track", "Multiplication tables", "Solve the multiplication fact to move your kart.", multiplication],
    "3-3": [3, "Equal-Share Plate Divider", "Division as sharing", "Share every counter equally between the plates.", sharing],
    "3-4": [3, "Jump-Back Number Line Divider", "Division", "Find how many equal jumps reach zero.", division],
    "3-5": [3, "Fraction Pie Builder", "Introducing fractions", "Shade the requested number of equal parts.", fractionParts],
    "3-6": [3, "Fraction Bar Comparator", "Comparing fractions", "Choose the fraction that is greater.", compareFractions],
    "3-7": [3, "Fence-the-Shape Perimeter Walker", "Perimeter", "Add every side to find the distance around the shape.", perimeter],
    "3-8": [3, "Precision Analog Clock Trainer", "Time", "Set the clock to the requested five-minute time.", clock],
    "3-9": [3, "Pictograph Builder", "Data handling", "Read the pictograph and answer the data question.", pictograph],
    "3-10": [3, "Round-to-Nearest-10 Slider", "Mental math", "Round the number to the nearest ten.", rounding],
    "3-11": [3, "Cashier Change-Maker", "Money", "Work out the change from a £20 note.", changeMaker],
    "4-1": [4, "Factor Tree Constructor", "Factors & multiples", "Choose the complete prime factorisation.", factorisation],
    "4-2": [4, "Factor Set Sorter", "LCM & HCF", "Find the highest common factor of two numbers.", hcf],
    "4-3": [4, "Long Division Quiz", "Long division", "Solve the division problem and choose the quotient.", longDivision],
    "4-4": [4, "Decimal Place-Value Grid", "Decimal notation", "Choose the decimal represented by the place-value grid.", decimals],
    "4-5": [4, "Fraction-Decimal Matcher", "Decimal ↔ fraction", "Match the fraction to its decimal equivalent.", fractionDecimal],
    "4-6": [4, "Angle Type Quiz", "Angle types", "Classify the angle by its measure.", angles],
    "4-7": [4, "Line Symmetry Quiz", "Symmetry", "Choose whether the shape has the shown line of symmetry.", symmetry],
    "4-8": [4, "Rectangle Area Quiz", "Area", "Count the unit squares needed to cover the rectangle.", area],
    "4-9": [4, "Roman Numeral Quiz", "Roman numerals", "Choose the Roman numeral for the number.", roman],
    "4-10": [4, "Bar Graph Quiz", "Data handling", "Read the bars and identify the category with the greatest value.", barGraph],
    "4-11": [4, "Solid Identification Quiz", "3D shapes", "Identify the solid from its faces, edges, and vertices.", solids],
  };

  const key = document.body.dataset.tool;
  const definition = definitions[key];
  const root = document.getElementById("toolApp");
  if (!definition || !root) return;
  const [grade, title, topic, intro, render] = definition;
  let score = 0;
  const rand = (min, max) => Math.floor(Math.random() * (max - min + 1)) + min;
  const shuffle = (items) => [...items].sort(() => Math.random() - 0.5);
  const choices = (answer, distractors) => shuffle([...new Set([answer, ...distractors])]);
  function shell(board) {
    document.title = `${title} · Class ${grade} · Mathsversity`;
    root.innerHTML = `<div class="tool-head"><div><p class="eyebrow">CLASS ${grade} · ${topic.toUpperCase()}</p><h1>${title}</h1><p>${intro}</p></div><div class="score-pill"><span>Score</span><strong id="score">${score}</strong></div></div><div class="tool-board">${board}</div><div class="tool-actions"><button class="tool-btn" id="checkTool" type="button">Check answer</button><button class="tool-btn secondary" id="resetTool" type="button">New round</button><span class="feedback" id="feedback">Make your move.</span></div>`;
    window.mathsversityLibraries?.ready.then(() => window.mathsversityEnhanceTool?.(root));
  }
  function feedback(message, good) { const el = document.getElementById("feedback"); el.textContent = message; el.className = `feedback ${good ? "good" : "try"}`; }
  function award(message) { score += 1; document.getElementById("score").textContent = score; window.mathsversityFreemium?.consumeHeart(); feedback(message, true); window.mathsversityCelebrate?.(); }
  function mountSymmetryCanvas(answer, onSelect) {
    const host = document.querySelector("#symmetryCanvas");
    if (!host || !window.p5) return;
    host.innerHTML = "";
    new window.p5((p) => {
      p.setup = () => p.createCanvas(320, 190).parent(host);
      p.draw = () => {
        p.clear();
        p.fill(120, 137, 178);
        p.noStroke();
        p.textAlign(p.CENTER, p.CENTER);
        p.textSize(15);
        p.text("YES", 80, 170);
        p.text("NO", 240, 170);
        p.stroke(229, 138, 79);
        p.strokeWeight(2);
        p.drawingContext.setLineDash([8, 7]);
        p.line(160, 12, 160, 178);
        p.drawingContext.setLineDash([]);
        p.fill(109, 143, 240, 220);
        p.stroke(56, 88, 184);
        p.beginShape();
        p.vertex(76, 138); p.vertex(124, 52); p.vertex(160, 78);
        if (answer === "yes") p.vertex(196, 52);
        else p.vertex(208, 68);
        p.vertex(244, 138); p.endShape(p.CLOSE);
      };
      p.mousePressed = () => onSelect(p.mouseX < p.width / 2 ? "yes" : "no");
      p.noLoop();
    });
  }
  function bind(check) { document.getElementById("checkTool").onclick = check; document.getElementById("resetTool").onclick = () => render(); }
  function selectChoices(answer, labels = (x) => x) { document.querySelectorAll(".choice").forEach((button) => button.onclick = () => { document.querySelectorAll(".choice").forEach((item) => item.classList.remove("selected")); button.classList.add("selected"); }); bind(() => Number(document.querySelector(".choice.selected")?.dataset.answer) === answer ? award(`Correct — the answer is ${labels(answer)}.`) : feedback("Try again: use the information in the question.", false)); }
  function arrayBuilder() { const rows = rand(2, 5), cols = rand(2, 6); let r = 0, c = 0; shell(`<div class="prompt-card"><strong>Build ${rows} rows of ${cols}</strong><span>Rows × columns = ?</span></div><div class="choice-row"><button class="choice add-row">Add row</button><button class="choice add-col">Add column</button></div><div class="array-grid" id="arrayGrid"></div><div class="feedback">Rows: <strong id="rowRead">0</strong> · Columns: <strong id="colRead">0</strong> · Product: <strong id="productRead">0</strong></div>`); const draw = () => { document.getElementById("arrayGrid").innerHTML = Array.from({length:r}, () => `<div class="array-row">${Array.from({length:c}, () => '<i></i>').join("")}</div>`).join(""); document.getElementById("rowRead").textContent=r; document.getElementById("colRead").textContent=c; document.getElementById("productRead").textContent=r*c; }; document.querySelector(".add-row").onclick=()=>{if(r<6)r++;draw()}; document.querySelector(".add-col").onclick=()=>{if(c<8)c++;draw()}; bind(()=>r===rows&&c===cols?award(`${rows} × ${cols} = ${rows*cols}.`):feedback(`Build exactly ${rows} rows and ${cols} columns.`,false)); }
  function multiplication() { const a=rand(3,9), b=rand(2,10), answer=a*b; shell(`<div class="prompt-card"><strong>${a} × ${b} = ?</strong><span>Choose the product to move your kart.</span></div><div class="race-track"><span>🏁</span><i style="width:${Math.min(90, a*b/90*100)}%"></i>🏎️</div><div class="choice-row">${choices(answer,[answer+a,answer-b,answer+10]).map(n=>`<button class="choice" data-answer="${n}">${n}</button>`).join("")}</div>`); selectChoices(answer); }
  function sharing() { const groups=rand(2,5), each=rand(3,8), total=groups*each; shell(`<div class="prompt-card"><strong>Share ${total} counters between ${groups} plates</strong><span>How many counters go on each plate?</span></div><div class="plate-row">${Array.from({length:groups},(_,i)=>`<div class="plate"><b>Plate ${i+1}</b><span>${each} counters</span></div>`).join("")}</div><div class="choice-row">${choices(each,[each-1,each+2,each+groups]).map(n=>`<button class="choice" data-answer="${n}">${n}</button>`).join("")}</div>`); selectChoices(each); }
  function division() { const q=rand(2,9), d=rand(2,9), answer=q*d; shell(`<div class="prompt-card"><strong>${answer} ÷ ${d} = ?</strong><span>Each backward jump is ${d}. Count the jumps to zero.</span></div><div class="jump-line">${Array.from({length:q+1},(_,i)=>`<span>${answer-i*d}</span>`).join("<b>←</b>")}</div><div class="choice-row">${choices(q,[q-1,q+1,q+3]).map(n=>`<button class="choice" data-answer="${n}">${n} jumps</button>`).join("")}</div>`); selectChoices(q); }
  function fractionParts() { const denominator=rand(3,8), numerator=rand(1,denominator-1); shell(`<div class="prompt-card"><strong>Shade ${numerator}/${denominator}</strong><span>How many equal parts should be shaded?</span></div><div class="fraction-bar">${Array.from({length:denominator},(_,i)=>`<i data-part="${i}"></i>`).join("")}</div><div class="choice-row">${choices(numerator,[numerator-1,numerator+1,denominator-numerator]).map(n=>`<button class="choice" data-answer="${n}">${n} parts</button>`).join("")}</div>`); document.querySelectorAll(".fraction-bar i").forEach((part,i)=>part.onclick=()=>part.classList.toggle("filled")); bind(()=>Number(document.querySelector(".choice.selected")?.dataset.answer)===numerator&&document.querySelectorAll(".fraction-bar .filled").length===numerator?award(`Correct — ${numerator} of ${denominator} parts are shaded.`):feedback(`Shade ${numerator} parts and choose ${numerator}.`,false)); }
  function compareFractions() { const den=rand(4,10), a=rand(1,den-1), b=rand(1,den-1); const left=`${a}/${den}`, right=`${b}/${den}`, answer=a>b?">":a<b?"<":"="; shell(`<div class="prompt-card"><strong>${left} &nbsp; ? &nbsp; ${right}</strong><span>These fractions have the same denominator. Compare the numerators.</span></div><div class="fraction-compare"><i style="width:${a/den*100}%">${left}</i><i style="width:${b/den*100}%">${right}</i></div><div class="choice-row">${["<","=",">"].map(n=>`<button class="choice" data-answer="${n}">${n}</button>`).join("")}</div>`); document.querySelectorAll(".choice").forEach(b=>b.onclick=()=>{document.querySelectorAll(".choice").forEach(x=>x.classList.remove("selected"));b.classList.add("selected")}); bind(()=>document.querySelector(".choice.selected")?.dataset.answer===answer?award(`${left} ${answer} ${right}.`):feedback("Look at the numerators: the denominator is the same.",false)); }
  function perimeter() { const w=rand(3,12), h=rand(2,9), answer=2*(w+h); shell(`<div class="prompt-card"><strong>Find the perimeter</strong><span>Every grid square is 1 cm. The rectangle is ${w} cm by ${h} cm.</span></div><div class="rectangle-shape" style="--w:${w};--h:${h}"><span>${w} cm</span><span>${h} cm</span></div><div class="choice-row">${choices(answer,[answer-2,answer+2,w*h]).map(n=>`<button class="choice" data-answer="${n}">${n} cm</button>`).join("")}</div>`); selectChoices(answer); }
  function clock() { const hour=rand(1,12), minute=rand(0,11)*5; shell(`<div class="prompt-card"><strong>Show ${hour}:${String(minute).padStart(2,"0")}</strong><span>Set both hands to the target time.</span></div><div class="clock-face"><div class="hand hour-hand"></div><div class="hand minute-hand"></div><div class="clock-center"></div></div><label>Hour <input id="hourRange" type="range" min="1" max="12" value="1"></label><label>Minute <input id="minuteRange" type="range" min="0" max="55" step="5" value="0"></label><div class="feedback">Time: <strong id="timeRead">1:00</strong></div>`); let h=1,m=0; const draw=()=>{document.querySelector(".hour-hand").style.transform=`rotate(${h*30+m*.5}deg)`;document.querySelector(".minute-hand").style.transform=`rotate(${m*6}deg)`;document.getElementById("timeRead").textContent=`${h}:${String(m).padStart(2,"0")}`}; document.getElementById("hourRange").oninput=e=>{h=Number(e.target.value);draw()};document.getElementById("minuteRange").oninput=e=>{m=Number(e.target.value);draw()};draw();bind(()=>h===hour&&m===minute?award(`That shows ${hour}:${String(minute).padStart(2,"0")}.`):feedback("Check the short hour hand and long minute hand.",false)); }
  function pictograph() { const data=[rand(2,8),rand(2,8),rand(2,8),rand(2,8)], labels=["Apples","Pears","Plums","Oranges"], max=Math.max(...data), answer=labels[data.indexOf(max)]; shell(`<div class="prompt-card"><strong>Which fruit was picked most?</strong><span>Each ● represents one fruit.</span></div><div class="data-table">${labels.map((l,i)=>`<div><b>${l}</b><span>${"● ".repeat(data[i])}</span><em>${data[i]}</em></div>`).join("")}</div><div class="choice-row">${shuffle(labels).map(l=>`<button class="choice" data-answer="${l}">${l}</button>`).join("")}</div>`); document.querySelectorAll(".choice").forEach(b=>b.onclick=()=>{document.querySelectorAll(".choice").forEach(x=>x.classList.remove("selected"));b.classList.add("selected")}); bind(()=>document.querySelector(".choice.selected")?.dataset.answer===answer?award(`${answer} has the greatest number.`):feedback("Compare the lengths of the pictograph rows.",false)); }
  function rounding() { const n=rand(11,99), answer=Math.round(n/10)*10; shell(`<div class="prompt-card"><strong>Round ${n} to the nearest 10</strong><span>Is it closer to ${answer-10} or ${answer}?</span></div><input id="roundSlider" type="range" min="0" max="100" value="50"><div class="number-scale"><span>${answer-10}</span><strong id="roundRead">50</strong><span>${answer}</span></div><div class="choice-row">${choices(answer,[answer-10,answer+10]).map(x=>`<button class="choice" data-answer="${x}">${x}</button>`).join("")}</div>`); document.getElementById("roundSlider").oninput=e=>document.getElementById("roundRead").textContent=e.target.value; selectChoices(answer); }
  function changeMaker() { const price=rand(3,18), answer=20-price; shell(`<div class="prompt-card"><strong>A toy costs £${price}. You pay with £20.</strong><span>How much change should the cashier give?</span></div><div class="choice-row">${choices(answer,[answer-1,answer+1,price]).map(n=>`<button class="choice" data-answer="${n}">£${n}</button>`).join("")}</div>`); selectChoices(answer, n=>`£${n}`); }
  function factorisation() { const primes=[2,3,5,7], factors=shuffle(primes).slice(0,rand(2,3)), n=factors.reduce((a,b)=>a*b,1), answer=factors.sort((a,b)=>a-b).join(" × "); shell(`<div class="prompt-card"><strong>Build the factor tree for ${n}</strong><span>Choose the prime factors that multiply to ${n}.</span></div><div class="factor-tree"><span>${n}</span><i>↙ &nbsp; ↘</i><b>${factors.join(" &nbsp; × &nbsp; ")}</b></div><div class="choice-row">${shuffle([answer,`${factors[0]} × ${factors[factors.length-1]+1}`,`${factors[0]+1} × ${factors[1]}`]).map(x=>`<button class="choice" data-answer="${x}">${x}</button>`).join("")}</div>`); document.querySelectorAll(".choice").forEach(b=>b.onclick=()=>{document.querySelectorAll(".choice").forEach(x=>x.classList.remove("selected"));b.classList.add("selected")}); bind(()=>document.querySelector(".choice.selected")?.dataset.answer===answer?award(`${n} = ${answer}.`):feedback("Prime factors are numbers greater than 1 with only two factors.",false)); }
  function hcf() { const common=rand(2,6), a=common*rand(2,5), b=common*rand(2,6); const answer=common; shell(`<div class="prompt-card"><strong>Find the HCF of ${a} and ${b}</strong><span>Choose the greatest factor shared by both numbers.</span></div><div class="venn"><span>${a}</span><b>common factors</b><span>${b}</span></div><div class="choice-row">${choices(answer,[1,common+1,common*2]).map(n=>`<button class="choice" data-answer="${n}">${n}</button>`).join("")}</div>`); selectChoices(answer); }
  function longDivision() { const divisor=rand(2,9), quotient=rand(12,38), dividend=divisor*quotient; shell(`<div class="prompt-card"><strong>${dividend} ÷ ${divisor} = ?</strong><span>Use multiplication to check the quotient.</span></div><div class="division-pad"><span>${dividend}</span><i>÷ ${divisor}</i><b>?</b></div><div class="choice-row">${choices(quotient,[quotient-1,quotient+1,divisor*quotient]).map(n=>`<button class="choice" data-answer="${n}">${n}</button>`).join("")}</div>`); selectChoices(quotient); }
  function decimals() { const tenths=rand(1,9), hundredths=rand(0,9), answer=Number(`0.${tenths}${hundredths}`); shell(`<div class="prompt-card"><strong>Build the decimal</strong><span>${tenths} tenths and ${hundredths} hundredths = ?</span></div><div class="place-grid"><b>Ones</b><b>Tenths</b><b>Hundredths</b><span>0</span><span>${tenths}</span><span>${hundredths}</span></div><div class="choice-row">${choices(answer,[Number(`0.${hundredths}${tenths}`),Number(`0.${tenths+1}${hundredths}`),Number(`0.${tenths}${hundredths+1}`)]).map(n=>`<button class="choice" data-answer="${n}">${n.toFixed(2)}</button>`).join("")}</div>`); selectChoices(answer, n=>n.toFixed(2)); }
  function fractionDecimal() { const pairs=[[1,.5],[1,.25],[3,.75],[1,.2],[2,.4],[4,.8]], [numerator,answer]=pairs[rand(0,pairs.length-1)], denominator=answer===.5?2:answer===.25?4:answer===.75?4:answer===.2?5:5; shell(`<div class="prompt-card"><strong>Match ${numerator}/${denominator} to a decimal</strong><span>Use the hundredths grid idea.</span></div><div class="decimal-meter"><i style="width:${answer*100}%"></i></div><div class="choice-row">${choices(answer,[.2,.4,.6,.8]).map(n=>`<button class="choice" data-answer="${n}">${n.toFixed(2)}</button>`).join("")}</div>`); selectChoices(answer, n=>n.toFixed(2)); }
  function angles() { const answer=rand(10,170), type=answer<90?"acute":answer===90?"right":"obtuse"; shell(`<div class="prompt-card"><strong>${answer}° angle</strong><span>Spin the ray and identify its type.</span></div><div class="angle-drawing"><i style="transform:rotate(${answer}deg)"></i></div><div class="choice-row">${["acute","right","obtuse"].map(x=>`<button class="choice" data-answer="${x}">${x}</button>`).join("")}</div>`); document.querySelectorAll(".choice").forEach(b=>b.onclick=()=>{document.querySelectorAll(".choice").forEach(x=>x.classList.remove("selected"));b.classList.add("selected")}); bind(()=>document.querySelector(".choice.selected")?.dataset.answer===type?award(`${answer}° is ${type}.`):feedback("Acute is less than 90°, right is 90°, obtuse is greater than 90°.",false)); }
  function symmetry() { const answer=Math.random()>.5?"yes":"no"; let selected=""; shell(`<div class="prompt-card"><strong>Does this shape have vertical line symmetry?</strong><span>Click YES or NO on the canvas.</span></div><div class="symmetry-shape" id="symmetryCanvas" aria-label="Interactive symmetry shape"></div><p class="canvas-selection" id="symmetrySelection">No answer selected</p>`); window.mathsversityLibraries?.ready.then(()=>mountSymmetryCanvas(answer,(choice)=>{selected=choice;document.getElementById("symmetrySelection").textContent=`Selected: ${choice.toUpperCase()}`})); bind(()=>selected===answer?award("Correct — you spotted the symmetry."):feedback(selected?"That choice does not match the shape.":"Click YES or NO on the canvas first.",false)); }
  function area() { const w=rand(3,9), h=rand(2,7), answer=w*h; shell(`<div class="prompt-card"><strong>Find the area</strong><span>A rectangle is ${w} squares wide and ${h} squares high. Each square is 1 cm².</span></div><div class="area-grid" style="--w:${w};--h:${h}">${Array.from({length:answer},()=>'<i></i>').join("")}</div><div class="choice-row">${choices(answer,[answer-w,answer+w,w+h]).map(n=>`<button class="choice" data-answer="${n}">${n} cm²</button>`).join("")}</div>`); selectChoices(answer); }
  function roman() { const map=[[4,"IV"],[9,"IX"],[14,"XIV"],[19,"XIX"],[24,"XXIV"],[29,"XXIX"],[34,"XXXIV"],[39,"XXXIX"],[44,"XLIV"],[49,"XLIX"]], [number,answer]=map[rand(0,map.length-1)]; shell(`<div class="prompt-card"><strong>Write ${number} in Roman numerals</strong><span>Build the numeral in the correct order.</span></div><div class="roman-blocks">${answer.split("").map(x=>`<i>${x}</i>`).join("")}</div><div class="choice-row">${shuffle([answer,answer.replace("X","V"),answer+"I"]).map(x=>`<button class="choice" data-answer="${x}">${x}</button>`).join("")}</div>`); document.querySelectorAll(".choice").forEach(b=>b.onclick=()=>{document.querySelectorAll(".choice").forEach(x=>x.classList.remove("selected"));b.classList.add("selected")}); bind(()=>document.querySelector(".choice.selected")?.dataset.answer===answer?award(`${number} is ${answer}.`):feedback("Remember that I is 1, V is 5, X is 10, and subtractive pairs come first.",false)); }
  function barGraph() { const labels=["Red","Blue","Green","Yellow"], values=labels.map(()=>rand(2,9)), answer=labels[values.indexOf(Math.max(...values))]; shell(`<div class="prompt-card"><strong>Which colour has the greatest value?</strong><span>Read the heights of the bars.</span></div><div class="bar-graph">${labels.map((l,i)=>`<div><i style="height:${values[i]*18}px"></i><b>${l}</b></div>`).join("")}</div><div class="choice-row">${shuffle(labels).map(x=>`<button class="choice" data-answer="${x}">${x}</button>`).join("")}</div>`); document.querySelectorAll(".choice").forEach(b=>b.onclick=()=>{document.querySelectorAll(".choice").forEach(x=>x.classList.remove("selected"));b.classList.add("selected")}); bind(()=>document.querySelector(".choice.selected")?.dataset.answer===answer?award(`${answer} has the tallest bar.`):feedback("Compare the bar heights carefully.",false)); }
  function solids() { const items=[ ["cube",6,12,8],["triangular prism",5,9,6],["square pyramid",5,8,5],["triangular pyramid",4,6,4] ], item=items[rand(0,items.length-1)]; shell(`<div class="prompt-card"><strong>Identify the solid</strong><span>${item[1]} faces, ${item[2]} edges, and ${item[3]} vertices.</span></div><div class="solid-cards">${items.map(x=>`<button class="choice" data-answer="${x[0]}">${x[0]}</button>`).join("")}</div>`); document.querySelectorAll(".choice").forEach(b=>b.onclick=()=>{document.querySelectorAll(".choice").forEach(x=>x.classList.remove("selected"));b.classList.add("selected")}); bind(()=>document.querySelector(".choice.selected")?.dataset.answer===item[0]?award(`Yes — that is a ${item[0]}.`):feedback("Use the faces, edges, and vertices as clues.",false)); }
  render();
})();
