class MathsversityFreemium{
  constructor(options={}){this.storageKey=options.storageKey||'mv_freemium_state';this.maxHearts=options.maxHearts||3;this.state=this._loadState();this._checkDailyReset();window.addEventListener('storage',e=>{if(e.key===this.storageKey){this.state=this._loadState();this._syncIndicators();this._dispatch('mv:stateSynced',{...this.state})}});this._syncIndicators()}
  _todayISO(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
  _loadState(){try{const raw=localStorage.getItem(this.storageKey);if(raw){const parsed=JSON.parse(raw);return {...this._defaults(),...parsed}}}catch(err){console.warn('Mathsversity: corrupted freemium state, resetting.',err)}return this._defaults()}
  _defaults(){return{hearts:this.maxHearts,lastResetDate:this._todayISO(),totalAttemptsToday:0,streakDays:0}}
  _saveState(){localStorage.setItem(this.storageKey,JSON.stringify(this.state));this._syncIndicators()}
  _checkDailyReset(){const today=this._todayISO();if(this.state.lastResetDate!==today){const wasActiveYesterday=this.state.totalAttemptsToday>0;this.state={...this.state,hearts:this.maxHearts,lastResetDate:today,totalAttemptsToday:0,streakDays:wasActiveYesterday?this.state.streakDays+1:0};this._saveState();this._dispatch('mv:heartsReset',{hearts:this.state.hearts})}}
  _syncIndicators(){document.querySelectorAll('[data-mv-hearts]').forEach(el=>{el.textContent='♥ '.repeat(this.state.hearts)+'♡ '.repeat(this.maxHearts-this.state.hearts);el.setAttribute('aria-label',`${this.state.hearts} of ${this.maxHearts} energy hearts remaining`)});document.querySelectorAll('[data-mv-attempts]').forEach(el=>el.textContent=this.state.totalAttemptsToday)}
  _dispatch(name,detail){window.dispatchEvent(new CustomEvent(name,{detail}))}
  canPlay(){this._checkDailyReset();return this.state.hearts>0}
  getHearts(){return this.state.hearts}
  consumeHeart(){if(!this.canPlay())return false;this.state.hearts-=1;this.state.totalAttemptsToday+=1;this._saveState();this._dispatch('mv:heartConsumed',{hearts:this.state.hearts});if(this.state.hearts===0)this.showParentModal();return true}
  grantBonusHeart(count=1){this.state.hearts=Math.min(this.maxHearts,this.state.hearts+count);this._saveState();this._dispatch('mv:bonusHearts',{hearts:this.state.hearts})}
  showParentModal(){if(document.getElementById('mv-paywall-modal'))return;const overlay=document.createElement('div');overlay.id='mv-paywall-modal';overlay.className='mv-modal-overlay';overlay.innerHTML=`<div class="mv-modal-card" role="dialog" aria-modal="true" aria-labelledby="mv-paywall-title"><button class="mv-modal-close" id="mv-close-x" aria-label="Close">×</button><div class="mv-modal-icon">♥</div><p class="mv-modal-eyebrow">A NOTE FOR GROWN-UPS</p><h2 id="mv-paywall-title">Great practice today!</h2><p>Your child has used all 3 free Energy Hearts for today. Hearts refill automatically at local midnight, or unlock unlimited practice with Mathsversity Premium.</p><a id="mv-upgrade-btn" class="mv-btn-primary" href="premium.html">See Premium Plans <span>→</span></a><button id="mv-close-btn" class="mv-btn-secondary">Maybe Later</button></div>`;document.body.appendChild(overlay);const close=()=>overlay.remove();document.getElementById('mv-close-btn').addEventListener('click',close);document.getElementById('mv-close-x').addEventListener('click',close);overlay.addEventListener('click',e=>{if(e.target===overlay)close()});this._dispatch('mv:paywallShown',{})}
}
window.mathsversityFreemium=new MathsversityFreemium();
